ARG NEXT_APP
FROM node:20 AS build

WORKDIR /usr/src/app

COPY apps/${NEXT_APP}/package*.json ./
RUN npm ci

COPY apps/${NEXT_APP}/ ./

ENV NODE_ENV=production
RUN npm run build

FROM node:20 AS runtime

WORKDIR /usr/src/app
ENV NODE_ENV=production

COPY --from=build /usr/src/app/.next ./.next
COPY --from=build /usr/src/app/node_modules ./node_modules
COPY --from=build /usr/src/app/package*.json ./

EXPOSE 3000
CMD ["npm", "start"]